### PR TITLE
Fix TypeScript Declaration

### PR DESCRIPTION
**Pull request by styfle**
This is pulling the upstream change from https://github.com/kaelzhang/node-ignore/blob/master/index.d.ts

It will also make the type match the canonical [node-ignore](https://github.com/kaelzhang/node-ignore/blob/master/index.d.ts).

### CODE REVIEW

**Comment by TooTallNate** [comment]
I'm not familiar with the difference between these two syntaxes. Can you explain?

**Comment by styfle** [comment]
@TooTallNate This is for the purpose of https://github.com/zeit/now-cli/pull/2207

There isn't much difference, `export = ignore` only works for Node.js sources since it matches the `module.exports = ignore`. But with ESM, this the the default export.

Usually this isn't a problem because of `esModuleInterop=true` but in PR 2207, you can see we use `const ignoreInit = (dockerIgnore === null ? ignore : dockerignore)` so that means `ignore` and `dockerignore` must be the exact same type 😄

**Comment by TooTallNate** [comment]
AppVeyor tests don't seem to be configured properly. We should set up CircleCI?

**Comment by styfle** [comment]
@TooTallNate Sounds like a good idea

**Comment by styfle** [comment]
@TooTallNate Circle CI is already setup 🤔  https://circleci.com/gh/zeit/dockerignore/70

**Pull request merged**
